In [ ]:
import pandas as pd
import numpy as np
np_array = np.random.rand(4,4)
df = pd.DataFrame(np_array)
print(df)

          0         1         2         3
0  0.497626  0.452758  0.231998  0.050002
1  0.762609  0.891099  0.014926  0.476424
2  0.479930  0.763710  0.540820  0.976153
3  0.269544  0.233612  0.451397  0.350792

In [ ]:
df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']

In [ ]:
print(df)

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.497626        0.452758        0.231998        0.050002
1        0.762609        0.891099        0.014926        0.476424
2        0.479930        0.763710        0.540820        0.976153
3        0.269544        0.233612        0.451397        0.350792

In [ ]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.502427        0.585295        0.309786        0.463343
std          0.202038        0.298102        0.235530        0.385860
min          0.269544        0.233612        0.014926        0.050002
25%          0.427333        0.397971        0.177730        0.275594
50%          0.488778        0.608234        0.341698        0.413608
75%          0.563872        0.795558        0.473753        0.601356
max          0.762609        0.891099        0.540820        0.976153

In [ ]:
print(df.isnull())
print(df.dtypes)

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False
Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [ ]:
df.loc[:, ['Random value 2', 'Random value 3']]

   Random value 2  Random value 3
0        0.452758        0.231998
1        0.891099        0.014926
2        0.763710        0.540820
3        0.233612        0.451397

In [ ]:
import pandas as pd
import numpy as np
np_array = np.random.rand(10,5)
df1 = pd.DataFrame(np_array)
print(df1)

          0         1         2         3         4
0  0.978968  0.949171  0.614201  0.008477  0.776719
1  0.662897  0.439389  0.054909  0.734703  0.134941
2  0.150175  0.061453  0.617897  0.345158  0.863864
3  0.862539  0.721071  0.675369  0.584892  0.940413
4  0.408895  0.416606  0.670535  0.767808  0.764317
5  0.172025  0.101542  0.609437  0.647387  0.095104
6  0.407247  0.127201  0.010733  0.676349  0.417848
7  0.142556  0.407907  0.601929  0.198516  0.746537
8  0.185478  0.995592  0.173315  0.361718  0.404280
9  0.995375  0.698654  0.354116  0.446158  0.740383

In [ ]:
print(df1)

          0         1         2         3         4
0  0.978968  0.949171  0.614201  0.008477  0.776719
1  0.662897  0.439389  0.054909  0.734703  0.134941
2  0.150175  0.061453  0.617897  0.345158  0.863864
3  0.862539  0.721071  0.675369  0.584892  0.940413
4  0.408895  0.416606  0.670535  0.767808  0.764317
5  0.172025  0.101542  0.609437  0.647387  0.095104
6  0.407247  0.127201  0.010733  0.676349  0.417848
7  0.142556  0.407907  0.601929  0.198516  0.746537
8  0.185478  0.995592  0.173315  0.361718  0.404280
9  0.995375  0.698654  0.354116  0.446158  0.740383

In [ ]:
df1.describe()

               0          1          2          3          4
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.496615   0.491859   0.438244   0.477117   0.588441
std     0.350587   0.340624   0.265936   0.249462   0.302997
min     0.142556   0.061453   0.010733   0.008477   0.095104
25%     0.175388   0.197377   0.218515   0.349298   0.407672
50%     0.408071   0.427998   0.605683   0.515525   0.743460
75%     0.812629   0.715467   0.616973   0.669109   0.773619
max     0.995375   0.995592   0.675369   0.767808   0.940413

In [ ]:
df1.loc[3, ]

0    0.862539
1    0.721071
2    0.675369
3    0.584892
4    0.940413
Name: 3, dtype: float64

In [ ]:
print(df1.isnull())

       0      1      2      3      4
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False
8  False  False  False  False  False
9  False  False  False  False  False